version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      docker: 19
      php: 7.3

  build:
    commands:
      # Install GH CLI
      - curl https://cli.github.com/packages/rpm/gh-cli.repo --output /etc/yum.repos.d/gh-cli.repo
      - yum install -y gh

      # Configure GitHub User & Branch
      - git config --global user.email "deleugyn+bref@gmail.com"
      - git config --global user.name "Brefphp Bot by @deleugyn"
      - git checkout master
      - git checkout -b bref/layers

      # Login to Docker Hub to avoid rate limit
      - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD

      # Necessary for publish.php to use Symfony Processor
      - make getcomposer
      - php composer.phar install

      # Copy AWS config to be able to automatically assume role into the layer account
      - mkdir ~/.aws && cp ./runtime/pipeline/config ~/.aws/config

      - make runtimes

      - make layers.json

      - |
        echo -en 'layers.json update\n\nCo-authored-by: Marco Deleu <deleugyn@gmail.com>' > git-message

      - git commit -a --file git-message

      - git remote add github https://brefphp-bot:${GITHUB_TOKEN}@github.com/brefphp-bot/bref.git
      - git push --set-upstream github bref/layers --force

      - gh pr create --title "New PHP Layers" --body "New layers have finished building" --repo "brefphp/bref" --base master --head "brefphp-bot:bref/layers"


